services:
  - type: web
    name: fixmyride-app
    env: node
    buildCommand: |
      echo "Current directory:"
      pwd
      echo "Directory contents:"
      ls
      echo "Installing root dependencies..."
      npm install
      echo "Building frontend..."
      cd dashboard1/velocihelp-center-main
      npm install
      npm run build
      echo "Installing backend dependencies..."
      cd ../../backend
      npm install
    startCommand: node backend/server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://fixmyride-app.onrender.com
      - key: NODE_ENV
        value: production 