services:
  - type: web
    name: fixmyride-app
    env: node
    buildCommand: |
      pwd
      ls
      npm install
      npm install -D vite@latest @vitejs/plugin-react autoprefixer postcss tailwindcss
      npm install -g vite
      export PATH=$PATH:$(npm config get prefix)/bin
      npx vite build
      cd backend
      npm install
    startCommand: node backend/server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://fixmyride-app.onrender.com
      - key: NODE_ENV
        value: production 